[package]
name = "webserver-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
log = "0.4.17"
sha2 = "0.10.6"
simplelog = "0.12.1"
sqlite = "0.30.4"
